name: CI
on:
  - pull_request

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9.9.0

      - name: Set up Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run lint
        run: pnpm lint

  typecheck:
    name: Typecheck
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9.9.0

      - name: Set up Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - name: Clean install
        run: |
          pnpm store path
          pnpm install --frozen-lockfile
          pnpm recursive list

      - name: Run typecheck
        run: pnpm type-check

  run-tests:
    name: Run Tests
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: packages/core
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9.9.0

      - name: Set up Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        working-directory: ./
        run: pnpm install --frozen-lockfile

      - name: Run tests
        run: pnpm test
